name: Rust

on:
  push:
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check format
        run: |
          cargo fmt --manifest-path halide-cache/Cargo.toml --check
          cargo fmt --manifest-path lager/Cargo.toml --check
      - name: Run clippy
        run: |
          cargo clippy --manifest-path halide-cache/Cargo.toml
          cargo clippy --manifest-path lager/Cargo.toml

  debug-build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    env:
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
      CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
    steps:
      - uses: actions/checkout@v4
      - name: Install cross-compilation tools
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get -y update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
      - name: Build
        run: cargo build --verbose --manifest-path api/Cargo.toml --target ${{ matrix.target }}

  check-releasable:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          dry-run: true
          manifest-path: halide-cache/Cargo.toml
          bin: halide-cache
          archive: app-$target
          target: x86_64-unknown-linux-gnu
